server:
  port: 8180

domain:
  name: account

spring:
  application:
    name: awesome-account-service
  datasource:
    url: jdbc:mysql://localhost:3306/awesome
    username: root
    password: awesome-mariadb
    platform: mysql
    initialization-mode: always
#    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: labs
    password: awesome-rabbitmq
  cloud:
    stream:
      bindings:
        AccountOutput:
          destination: accountExchange
          content-type: application/json
      rabbit:
        bindings:
          AccountOutput:
            producer:
              routing-key-expression: headers['routeTo']

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"