server:
  port: 8184

domain:
  category:
    name: category
  product:
    name: product

spring:
  application:
    name: awesome-product-service
  datasource:
    url: jdbc:mysql://localhost:3310/awesome
    username: root
    password: awesome-mariadb
    platform: mysql
    initialization-mode: always
#    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: labs
    password: awesome-rabbitmq
  cloud:
    stream:
      bindings:
        orderCreated:
          destination: orderExchange
          group: product.orderCreated
          content-type: application/json
        orderCanceled:
          destination: orderExchange
          group: product.orderCanceled
          content-type: application/json
        ProductOutput:
          destination: productExchange
          content-type: application/json
      rabbit:
        bindings:
          orderCreated:
            consumer:
              autoBindDlq: true
              bindingRoutingKey: order.OrderCreated.#
          orderCanceled:
            consumer:
              autoBindDlq: true
              bindingRoutingKey: order.OrderCanceled.#
          ProductOutput:
            producer:
              routing-key-expression: headers['routeTo']

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"