server:
  port: 8182

domain:
  name: order
  
spring:
  application:
    name: awesome-order-service
  datasource:
    url: jdbc:mysql://localhost:3308/awesome
    username: root
    password: awesome-mariadb
    platform: mysql
    initialization-mode: always
#    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: labs
    password: awesome-rabbitmq
  cloud:
    stream:
      bindings:
        productAmountSubtractFailed:
          destination: productExchange
          group: order.productAmountSubtractFailed
          content-type: application/json
        paymentCreateFailed:
          destination: paymentExchange
          group: order.paymentCreateFailed
          content-type: application/json
        paymentPaid:
          destination: paymentExchange
          group: order.paymentPaid
          content-type: application/json
        paymentCreated:
          destination: paymentExchange
          group: order.paymentCreated
          content-type: application/json
        OrderOutput:
          destination: orderExchange
          content-type: application/json
      rabbit:
        bindings:
          productAmountSubtractFailed:
            consumer:
              autoBindDlq: true
              bindingRoutingKey: product.ProductAmountSubtractFailed.#
          paymentCreateFailed:
            consumer:
              autoBindDlq: true
              bindingRoutingKey: payment.PaymentCreateFailed.#  
          paymentPaid:
            consumer:
              autoBindDlq: true
              bindingRoutingKey: payment.PaymentPaid.# 
          paymentCreated:
            consumer:
              autoBindDlq: true
              bindingRoutingKey: payment.PaymentCreated.# 
          OrderOutput:
            producer:
              autoBindDlq: true
              routing-key-expression: headers['routeTo']
              

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"